In [38]:
import pandas as pd
from rag import get_embedding
import numpy as np
import torch
import torch.nn.functional as F
    

In [ ]:
df = pd.read_csv('smus_page.csv')
df.head()
df.shape
embeddings = get_embedding(df['Page Content'].iloc[0])
embeddings.shape

In [5]:
df['embeddings'] = df['Page Content'].apply(lambda x: get_embedding(str(x)) if isinstance(x, str) else None)
df.to_csv('smus_page_with_embeddings.csv', index=False)
df.to_pickle('smus_page_with_embeddings.pkl')

/opt/anaconda3/envs/voice-chat-python3-11/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


tensor([[[ 0.0672,  0.0504, -0.1421,  ..., -0.1023,  0.4395,  0.1785],
         [-0.2012,  0.7391, -0.1117,  ...,  0.2124,  0.4202,  0.5236],
         [-0.9448,  0.7462,  0.1136,  ..., -0.2321, -0.9359,  0.7445],
         ...,
         [-0.2628, -0.2890,  0.4341,  ...,  0.0885, -0.0631,  0.0398],
         [-0.5046, -0.1146,  0.2375,  ..., -0.1592,  0.3137, -0.2078],
         [-0.0866,  0.3321, -0.1068,  ...,  0.4328, -0.1631, -0.0539]]])
tensor([[[-0.2062, -0.2482, -0.0675,  ...,  0.2769,  0.2994,  0.4807],
         [ 0.1619,  0.4940, -0.1021,  ...,  0.2921,  0.8780,  0.2805],
         [-0.3544,  0.4755,  0.8103,  ...,  0.3974,  0.5345, -0.3593],
         ...,
         [-0.0271,  0.3903, -0.2786,  ...,  0.3235,  0.0936,  0.5592],
         [ 0.5317, -0.3789, -0.1974,  ...,  0.5242,  0.4188, -0.3078],
         [-0.0815,  0.5182, -0.2758,  ...,  0.6579,  0.2258,  0.1724]]])
tensor([[[ 0.2220, -0.1761,  0.0011,  ..., -0.0052,  0.6026,  0.0925],
         [-0.0148,  0.6306,  0.0198,  ...,  0

In [6]:
df = pd.read_pickle('./smus_page_with_embeddings.pkl')
df.head()

URL  \
0                          https://www.smus.ca/   
1                https://www.smus.ca/admissions   
2   https://www.smus.ca/admissions/publications   
3             https://www.smus.ca/middle-school   
4  https://www.smus.ca/admissions/international   

                                        Page Content  \
0     Explore \n      When you visit any website,...   
1     Thank you for choosing to discover more abo...   
2     If you are interested in learning more abou...   
3     The Middle School (Grades 6 to 8) program i...   
4     \n\n\n\n\n\n            Schaffter Hall for ...   

                                          embeddings  
0  [[[tensor(0.0672), tensor(0.0504), tensor(-0.1...  
1  [[[tensor(-0.2062), tensor(-0.2482), tensor(-0...  
2  [[[tensor(0.2220), tensor(-0.1761), tensor(0.0...  
3  [[[tensor(0.0071), tensor(-0.3182), tensor(-0....  
4  [[[tensor(0.0979), tensor(0.0549), tensor(-0.1...

In [12]:
question = "How many students are in SMUS 2024?"
question_embedding = get_embedding(question)
question, question_embedding[0:10]


/opt/anaconda3/envs/voice-chat-python3-11/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


tensor([[[ 1.2869e-01, -3.4062e-02,  3.3475e-01,  ..., -4.4159e-01,
           6.2480e-01,  3.2984e-01],
         [ 1.8853e-01, -2.8151e-02,  1.3130e-01,  ..., -3.5970e-02,
           5.9448e-01,  3.0285e-01],
         [ 1.1611e-01, -4.7668e-01,  6.3334e-01,  ..., -4.6434e-01,
           3.8071e-01,  7.6461e-04],
         ...,
         [-1.1828e-01, -5.1865e-01,  8.5562e-01,  ..., -4.2414e-01,
           4.3259e-01,  1.2262e-01],
         [-7.6620e-03, -5.2908e-02, -5.5358e-01,  ..., -6.8029e-03,
           6.4283e-01, -4.3157e-01],
         [ 6.8547e-01,  1.2927e-01,  4.5829e-02,  ...,  1.8805e-01,
          -6.5068e-01, -1.0143e-01]]])


('How many students are in SMUS 2024?',
 tensor([[[ 1.2869e-01, -3.4062e-02,  3.3475e-01,  ..., -4.4159e-01,
            6.2480e-01,  3.2984e-01],
          [ 1.8853e-01, -2.8151e-02,  1.3130e-01,  ..., -3.5970e-02,
            5.9448e-01,  3.0285e-01],
          [ 1.1611e-01, -4.7668e-01,  6.3334e-01,  ..., -4.6434e-01,
            3.8071e-01,  7.6461e-04],
          ...,
          [-1.1828e-01, -5.1865e-01,  8.5562e-01,  ..., -4.2414e-01,
            4.3259e-01,  1.2262e-01],
          [-7.6620e-03, -5.2908e-02, -5.5358e-01,  ..., -6.8029e-03,
            6.4283e-01, -4.3157e-01],
          [ 6.8547e-01,  1.2927e-01,  4.5829e-02,  ...,  1.8805e-01,
           -6.5068e-01, -1.0143e-01]]]))

In [41]:
# truncate the vector
def truncate_vector(tensor, target_length):
    current_length = tensor.size(1)  # Get the current sequence length

    # If the sequence is longer, truncate it
    if current_length > target_length:
        tensor = tensor[:, :target_length, :]  # Truncate to target_length

    # If the sequence is shorter, pad it
    elif current_length < target_length:
        padding = target_length - current_length
        tensor = F.pad(tensor, (0, 0, 0, padding))  # Pad on the right with zeros

    return tensor

In [44]:
truncated_question_embedding = truncate_vector(question_embedding, 128)
truncated_question_embedding.shape

torch.Size([1, 128, 768])

In [47]:
df['embeddings'].iloc[0]

tensor([[[ 0.0672,  0.0504, -0.1421,  ..., -0.1023,  0.4395,  0.1785],
         [-0.2012,  0.7391, -0.1117,  ...,  0.2124,  0.4202,  0.5236],
         [-0.9448,  0.7462,  0.1136,  ..., -0.2321, -0.9359,  0.7445],
         ...,
         [-0.2628, -0.2890,  0.4341,  ...,  0.0885, -0.0631,  0.0398],
         [-0.5046, -0.1146,  0.2375,  ..., -0.1592,  0.3137, -0.2078],
         [-0.0866,  0.3321, -0.1068,  ...,  0.4328, -0.1631, -0.0539]]])

In [48]:
df["embeddings"] = df["embeddings"].apply(lambda x: truncate_vector(x, 128) if x != None else None)
df.head()

URL  \
0                          https://www.smus.ca/   
1                https://www.smus.ca/admissions   
2   https://www.smus.ca/admissions/publications   
3             https://www.smus.ca/middle-school   
4  https://www.smus.ca/admissions/international   

                                        Page Content  \
0     Explore \n      When you visit any website,...   
1     Thank you for choosing to discover more abo...   
2     If you are interested in learning more abou...   
3     The Middle School (Grades 6 to 8) program i...   
4     \n\n\n\n\n\n            Schaffter Hall for ...   

                                          embeddings  
0  [[[tensor(0.0672), tensor(0.0504), tensor(-0.1...  
1  [[[tensor(-0.2062), tensor(-0.2482), tensor(-0...  
2  [[[tensor(0.2220), tensor(-0.1761), tensor(0.0...  
3  [[[tensor(0.0071), tensor(-0.3182), tensor(-0....  
4  [[[tensor(0.0979), tensor(0.0549), tensor(-0.1...

In [63]:
df["embeddings"].iloc[0].shape
truncated_question_embedding.shape

torch.Size([1, 128, 768])

In [70]:
def fn(page_embedding):
    print(page_embedding.shape)
    return torch.sum(page_embedding * truncated_question_embedding, dim=2)

In [97]:
df["distance"] = df["embeddings"].apply(lambda x: fn(x) if x != None else None)
df["distance"] = df["distance"].apply(lambda x: x.detach().numpy() if x != None else None)
df["distance"] = df["distance"].apply(lambda x: np.sum(x))

torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([1, 128, 768])
torch.Size([

In [100]:
df.sort_values(by='distance', ascending=True, inplace=True)
df

URL  \
95     https://www.smus.ca/news/a-warm-welcome-awaits   
96  https://www.smus.ca/news/gallery-happy-diwali-...   
53       https://www.smus.ca/news/diligence-and-focus   
32           https://www.smus.ca/news/coastal-cleanup   
33          https://www.smus.ca/news/portrait-learner   
..                                                ...   
29                        https://www.smus.ca/smusart   
13                          https://intranet.smus.ca/   
30                          https://api-beta.smus.ca/   
54                       https://api.smus.ca/register   
84                   https://api-latest.smus.ca/login   

                                         Page Content  \
95     \n              By\n                  Alexi...   
96     \n              By\n                  Kyle ...   
53     \n              By\n                  Denis...   
32     \n              By\n                  Kyle ...   
33     \n              By\n                  Jorda...   
..                                                ...   
29  JUMP TO THE LATEST ISSUE THE ART TEACHERS STUD...   
13                                                NaN   
30                                                NaN   
54                                                NaN   
84                                                NaN   

                                           embeddings    distance  
95  [[[tensor(-0.1761), tensor(-0.0835), tensor(-0...  588.806152  
96  [[[tensor(-0.3196), tensor(-0.1856), tensor(-0...  593.351685  
53  [[[tensor(-0.0353), tensor(-0.0131), tensor(-0...  617.067322  
32  [[[tensor(-0.0214), tensor(0.1590), tensor(0.0...  626.878479  
33  [[[tensor(0.1656), tensor(-0.3861), tensor(-0....  628.129761  
..                                                ...         ...  
29  [[[tensor(0.0400), tensor(-0.1418), tensor(-0....  888.390137  
13                                               None         NaN  
30                                               None         NaN  
54                                               None         NaN  
84                                               None         NaN  

[99 rows x 4 columns]